version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MODEL_PATH=models/diabetes_model.h5
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app
    working_dir: /app
